backbone: resnet32
n_epochs: 70
scheduler: multisteplr
optim_mom: 0.9
lr_milestones:
  - 49
  - 63
sched_multistep_lr_gamma: 0.2
batch_size: 128
seed: 1993
MEAN: [0.5071, 0.4867, 0.4408]
STD: [1, 1, 1]
TRANSFORM:
  - RandomCrop:
      size: 32
      padding: 4
  - RandomHorizontalFlip
  - ToTensor
  - Normalize:
      mean: [0.5071, 0.4867, 0.4408]
      std: [1, 1, 1]
TEST_TRANSFORM:
  - ToTensor
  - Normalize:
      mean: [0.5071, 0.4867, 0.4408]
      std: [1, 1, 1]
