seq-mnist:
  dataset_config: spr
  custom_class_order: 7,6,2,3,0,1,5,9,8,4
  300:
    noise: sym
    noise_rate: 0.2
    expert_train_epochs: 4000
    inner_train_epochs: 3000
    lr: 0.0003
    optimizer: adam 