N_TASKS: 10
N_CLASSES_PER_TASK: 10
N_CLASSES: 100
SIZE: [224, 224]
MEAN: [0.485, 0.456, 0.406]
STD: [0.229, 0.224, 0.225]
TRANSFORM:
  - RandomResizedCrop:
      size: 224
      interpolation: 3
  - RandomHorizontalFlip
  - ToTensor
  - Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
TEST_TRANSFORM:
  - Resize:
      size: 224
      interpolation: 3
  - ToTensor
  - Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
batch_size: 128
n_epochs: 20