N_TASKS: 10
N_CLASSES_PER_TASK: 10
N_CLASSES: 100
SIZE: [224, 224]
MEAN: [0.5, 0.5, 0.5]
STD: [0.5, 0.5, 0.5]
TRANSFORM:
    - RandomResizedCrop:
        size: 224
        interpolation: 3
    - RandomHorizontalFlip
    - ToTensor
    - Normalize:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
TEST_TRANSFORM:
    - Resize:
        size: 256
        interpolation: 3
    - CenterCrop:
        size: 224
    - ToTensor
    - Normalize:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
batch_size: 128
n_epochs: 20
optimizer: adamw